version: '2'

services:
  site:
    image: nginx
    container_name: taller-site
    volumes:
      - ./build:/usr/share/nginx/html
    environment:
      # Add this server to the proxy.
      - VIRTUAL_HOST=taller-site.dropit.in,stage.taller.net.br

networks:
  default:
    external:
      name: dockerproxy_service-tier
